package cmm.Absyn; // Java Package generated by the BNF Converter.

public abstract class CmpOp implements java.io.Serializable {
  public abstract <R,A> R accept(CmpOp.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(cmm.Absyn.OLt p, A arg);
    public R visit(cmm.Absyn.OGt p, A arg);
    public R visit(cmm.Absyn.OLtEq p, A arg);
    public R visit(cmm.Absyn.OGtEq p, A arg);
    public R visit(cmm.Absyn.OEq p, A arg);
    public R visit(cmm.Absyn.ONEq p, A arg);

  }

}
