package cmm.Absyn; // Java Package generated by the BNF Converter.

public class EAdd  extends Exp {
  public final Exp exp_1, exp_2;
  public final AddOp addop_;
  public EAdd(Exp p1, AddOp p2, Exp p3) { exp_1 = p1; addop_ = p2; exp_2 = p3; }

  public <R,A> R accept(cmm.Absyn.Exp.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof cmm.Absyn.EAdd) {
      cmm.Absyn.EAdd x = (cmm.Absyn.EAdd)o;
      return this.exp_1.equals(x.exp_1) && this.addop_.equals(x.addop_) && this.exp_2.equals(x.exp_2);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(this.exp_1.hashCode())+this.addop_.hashCode())+this.exp_2.hashCode();
  }


}
