package cmm.Absyn; // Java Package generated by the BNF Converter.

public class EBool  extends Exp {
  public final BoolLit boollit_;
  public EBool(BoolLit p1) { boollit_ = p1; }

  public <R,A> R accept(cmm.Absyn.Exp.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof cmm.Absyn.EBool) {
      cmm.Absyn.EBool x = (cmm.Absyn.EBool)o;
      return this.boollit_.equals(x.boollit_);
    }
    return false;
  }

  public int hashCode() {
    return this.boollit_.hashCode();
  }


}
