package cmm.Absyn; // Java Package generated by the BNF Converter.

public class EPost  extends Exp {
  public final String id_;
  public final IncDecOp incdecop_;
  public EPost(String p1, IncDecOp p2) { id_ = p1; incdecop_ = p2; }

  public <R,A> R accept(cmm.Absyn.Exp.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof cmm.Absyn.EPost) {
      cmm.Absyn.EPost x = (cmm.Absyn.EPost)o;
      return this.id_.equals(x.id_) && this.incdecop_.equals(x.incdecop_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.id_.hashCode())+this.incdecop_.hashCode();
  }


}
