package cmm.Absyn; // Java Package generated by the BNF Converter.

public abstract class IncDecOp implements java.io.Serializable {
  public abstract <R,A> R accept(IncDecOp.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(cmm.Absyn.OInc p, A arg);
    public R visit(cmm.Absyn.ODec p, A arg);

  }

}
