package cmm.Absyn; // Java Package generated by the BNF Converter.

public class ODiv  extends MulOp {
  public ODiv() { }

  public <R,A> R accept(cmm.Absyn.MulOp.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof cmm.Absyn.ODiv) {
      return true;
    }
    return false;
  }

  public int hashCode() {
    return 37;
  }


}
